/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sandun.web.template;

/**
 *
 * @author SANDUN BUDDHIKA
 */
public class MessageContainer extends javax.swing.JPanel {

    /**
     * Creates new form Message
     */
    public MessageContainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(755, 60));
        setMinimumSize(new java.awt.Dimension(755, 60));
        setPreferredSize(new java.awt.Dimension(755, 60));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
